// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwKOVRNxBqjkmdlyTe_s1YQMa3hxDcls4',
    appId: '1:966858969115:web:8e9e3e25e002e0e28da8be',
    messagingSenderId: '966858969115',
    projectId: 'whatsapp-backend-8fa5b',
    authDomain: 'whatsapp-backend-8fa5b.firebaseapp.com',
    storageBucket: 'whatsapp-backend-8fa5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7-dYNTcFkskO0TG60JLThFcmwHvmNKo',
    appId: '1:966858969115:android:1d5f7a1f151a7e1f8da8be',
    messagingSenderId: '966858969115',
    projectId: 'whatsapp-backend-8fa5b',
    storageBucket: 'whatsapp-backend-8fa5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ8R6RYE3j1TwwbeoTNWGDz7Qq_WoCa58',
    appId: '1:966858969115:ios:010e8e849e19153d8da8be',
    messagingSenderId: '966858969115',
    projectId: 'whatsapp-backend-8fa5b',
    storageBucket: 'whatsapp-backend-8fa5b.appspot.com',
    iosBundleId: 'com.example.whatsappclone',
  );
}
